### PR TITLE
Register form fix bugs

### PR DESCRIPTION
**Pull request by ftrenstein**

### CODE REVIEW

**Review by MaloP47 — APPROVED** [review]
Ok pour moi

**Comment by uotiug** [comment]
Capture d’écran 2024-07-21 à 11 47 16
please add rounded corner like the other 'hide/show password' btn, then, i'll accept it (you can push directly on your branch register_main, the PR we'll automatically update (je crois))

**Comment by ftrenstein** [comment]
add fix coin

**Review by uotiug — APPROVED** [review]
ok

**Pull request merged**
